// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhjoyvbwpphrtppqjdso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoam95dmJ3cHBocnRwcHFqZHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0ODI2NzIsImV4cCI6MjA1OTA1ODY3Mn0.xwY2shh5nKUvHjJUbB_3IEOGyByUSgoIhqEk_8RBrvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);